apiVersion: apps/v1
kind: Deployement
metadata:
  name: catalogue-deployement
  namespace: roboshop
  labels:
    app: catalogue
    tier: app
spec:
  selector:
    matchLabels:
      app: catalogue
      tier: app
    template:
      metadata:
        labels:
          app: catalogue
          tier: app
      spec:
        containers:
        - image: saivinaylt/catalogue:k8
          name: catalogue
          imagePullPolicy: Always