kind: Deployment
apiVersion: apps/v1
metadata:
  namespace: roboshop
  name: web
spec:
  replicas: 1
  selector:
    matchLabels:
      name: web
      tier: DB
  template:
    metadata:
      labels:
        name: web
        tier: DB
    spec: 
      containers:
      - image: saivinaylt/web:k8
        name: web
        imagePullPolocy: Alway

---
kind: Service
apiVersion: v1
metadata: 
  name: webservice
  namespace: roboshop
spec:
  type: LoadBalancer
  selector:
    name: web
    tier: DB
  ports:
  - name: webport
    protocol: TCP
    port: 80
    targetPort: 80



