kind: Deployement
apiVersion: apps/v1
metadata:
  name: web
  namespace: roboshop
spec:
  replicas: 1
  selector:
    matchLabels:
      name: web
      tier: app
  template:
    metadata:
      labels:
        name: mongodb
        tier: DB
    spec: 
      containers:
      - image: saivinaylt/web:k8
        name: web
        imagePullPolocy: Always


  


