kind: Deployment
apiVersion: apps/v1
metadata:
  name: web
  namespace: roboshop
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web
      kind: frontend
  template:
    metadata:
      labels:
        app: web
        kind: frontend
    spec:
      containers:
      - name: web
        imagePullPolicy: Always
        image: saivinaylt/web:k8

---
kind: Service
apiVersion: v1
metadata:
  name: webservice
  namespace: roboshop
spec:
  type: LoadBalancer
  selector:
    app: web
    kind: frontend
  ports;
  - name: webport
    protocol: TCP
    port: 80
    targetPort: 80



