kind: Deployement
apiVersion: apps/v1
metadata:
  name: web
spec:
  selector:
    matchLabels:
      name: web
      tier: DB
  template:
    metadata:
      labels:
        name: web
        tier: DB
    spec: 
      containers:
      - image: saivinaylt/web:k8
        name: web
        imagePullPolocy: Always